yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

from posts.views import (index, group_posts, profile,
                         post_detail, post_create, post_edit, add_comment)

app_name = 'posts'

urlpatterns = [
    path('', index, name='index'),
    path('create/', post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', post_edit, name='post_edit'),
    path('group/<slug:slug>/', group_posts, name='group_list'),
    path('profile/<str:username>/', profile, name='profile'),
    path('posts/<int:post_id>/', post_detail, name='post_detail'),
    path('posts/<int:post_id>/comment/', add_comment, name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path('profile/<str:username>/follow/',
         views.profile_follow,
         name='profile_follow'
         ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('logout/',
         LogoutView.as_view(template_name='users/logged_out.html'),
         name='logout'
         ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),

    path('password_change/', views.password_change, name='password_change'),
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(),
         name='password_change_done'
         ),

    path('password_reset/',
         views.password_reset_request,
         name='password_reset'
         ),

    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name="users/password_reset_confirm.html"),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static


handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'

urlpatterns = [
    path('auth/', include('users.urls')),
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),

]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm

from django import forms


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        fields = ('first_name', 'last_name', 'username', 'email')


class EmailForm(forms.Form):
    recipient = forms.EmailField()
    message = forms.CharField(widget=forms.Textarea)

yatube/users/views.py
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm, PasswordResetForm
from django.contrib.auth.models import User
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import BadHeaderError, send_mail
from django.db.models.query_utils import Q
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.views.generic import CreateView

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'


def password_change(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request,
                             'Your password was successfully updated!')
            return redirect('users:login')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'users/password_change_form.html', {
        'form': form
    })


def password_reset_request(request):
    if request.method == "POST":
        password_reset_form = PasswordResetForm(request.POST)
        if password_reset_form.is_valid():
            data = password_reset_form.cleaned_data['email']
            associated_users = User.objects.filter(Q(email=data))
            if associated_users.exists():
                for user in associated_users:
                    subject = "Password Reset Requested"
                    email_template_name = "users//password_reset_email.txt"
                    c = {
                        "email": user.email,
                        'domain': '127.0.0.1:8000',
                        'site_name': 'Website',
                        "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                        "user": user,
                        'token': default_token_generator.make_token(user),
                        'protocol': 'http',
                    }
                    email = render_to_string(email_template_name, c)
                    try:
                        send_mail(subject, email, 'admin@example.com',
                                  [user.email], fail_silently=False)
                    except BadHeaderError:
                        return HttpResponse('Invalid header found.')
                    return redirect("/auth/password_reset/done/")
    password_reset_form = PasswordResetForm()
    return render(request=request,
                  template_name="users/password_reset_form.html",
                  context={"password_reset_form": password_reset_form})

yatube/templates/users/logged_out.html
{% load static %}
<html lang="ru">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="icon" href="../img/fav/fav.ico" type="image">
        <link rel="apple-touch-icon" sizes="180x180" href="../img/fav/apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="../img/fav/favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="../img/fav/favicon-16x16.png">
        <meta name="msapplication-TileColor" content="#da532c">
        <meta name="theme-color" content="#ffffff">
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <title>Вы вышли из системы</title>
    </head>
    <body>
        <header>
            <nav class="navbar navbar-light" style="background-color: lightskyblue">
                <div class="container">
                    <a class="navbar-brand" href="{% url 'posts:index' %}">
                        <img src="static/img/logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
                        <span style="color:red">Ya</span>tube</a>
                    <!--                <span style="color:red">Ya</span>tube-->
                </a>
            </div>
        </nav>
    </header>
    <main>
        <div class="container py-5">
            <div class="row justify-content-center">
                <div class="col-md-8 p-5">
                    <div class="card">
                        <div class="card-header">Выход</div>
                        <div class="card-body"><p>Вы вышли из своей учётной записи. Ждём вас снова!</p>
                        </div> <!-- card body -->
                    </div> <!-- card -->
                </div> <!-- col -->
            </div> <!-- row -->
        </div>
    </main>
    <footer class="border-top text-center py-3">
        <p>© 2021 Copyright <span style="color:red">Ya</span>tube</p>
    </footer>
</body>
</html>

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}
<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">
                Войти на сайт
            </div>
            <div class="card-body">
                {% include 'includes/form_errors.html' %}
                <form method="post"
                >
                    {% csrf_token %}
                    {% include 'includes/fields_form.html' %}
                    <div class="col-md-6 offset-md-4">
                        <button type="submit" class="btn btn-primary">
                            Войти
                        </button>
                        <a href="{% url 'users:password_reset' %}"
                           class="btn btn-link">
                            Забыли пароль?
                        </a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

yatube/templates/users/password_change_done.html
<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="icon" href="../img/fav/fav.ico" type="image">
        <link rel="apple-touch-icon" sizes="180x180" href="../img/fav/apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="../img/fav/favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="../img/fav/favicon-16x16.png">
        <meta name="msapplication-TileColor" content="#da532c">
        <meta name="theme-color" content="#ffffff">
        <link rel="stylesheet" href="../css/bootstrap.min.css">
        <title>Пароль изменён</title>
    </head>
    <body>
        <header>
            <nav class="navbar navbar-light" style="background-color: lightskyblue">
                <div class="container">
                    <a class="navbar-brand" href="../posts/index.html">
                        <img src="../img/logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
                        <span style="color:red">Ya</span>tube
                    </a>
                </div>
            </nav>
        </header>
        <main>
            <div class="container py-5">
                <div class="row justify-content-center">
                    <div class="col-md-8 p-5">
                        <div class="card">
                            <div class="card-header">
                                Пароль изменён
                            </div>
                            <div class="card-body">
                                <p>Пароль изменён успешно</p>
                            </div> <!-- card body -->
                        </div> <!-- card -->
                    </div> <!-- col -->
                </div> <!-- row -->
            </div>
        </main>
        <footer class="border-top text-center py-3">
            <p>© 2021 Copyright <span style="color:red">Ya</span>tube</p>
        </footer>
    </body>
</html>

yatube/templates/users/password_change_form.html
{% extends "base.html" %}
{% block title %}Смена пароля{% endblock %}
{% block content %}
    {% load user_filters %}
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Save changes</button>
    </form>
{% endblock %}

yatube/templates/users/password_reset.html
{% extends 'base.html' %}

{% block title %}Forgot Your Password?{% endblock %}

{% block content %}
    <h1>Forgot your password?</h1>
    <p>Enter your email address below, and we'll email instructions for setting a new one.</p>

    <form method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Send me instructions!">
    </form>
{% endblock %}

yatube/templates/users/password_reset_complete.html
{% extends "base.html" %}
{% block title %}Сброс пароля{% endblock %}


{% block content %}

    <!--Password Reset Complete-->
    <div class="container p-4">
        <h2 class="font-weight-bold mt-3">Password reset complete</h2>
        <hr>
        <p>Your password has been set. You may go ahead and log in now.</p>
        <a href="{% url 'users:login' %}" class="btn btn-link">
            <!--    <a href="/login" class="btn btn-primary">Log in</a>-->
        </div>

{% endblock %}

yatube/templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% block title %}Сброс пароля{% endblock %}


{% block content %}

    {% load user_filters %}

    <!--Password Reset Confirm-->
    <div class="container p-5">
        <h2 class="font-weight-bold mt-3">Password Reset Confirm</h2>
        <hr>
        <p>Please enter your new password.</p>
        <form method="POST">
            {% csrf_token %}
            {{ form }}
            <button class="btn btn-primary" type="submit">Reset password</button>
        </form>
    </div>

{% endblock %}

yatube/templates/users/password_reset_done.html
{% extends "base.html" %}
{% block title %}Сброс пароля{% endblock %}
{% block content %}

    <!--Password reset sent-->
    <div class="container p-5">
        <h2 class="font-weight-bold mt-3">Password reset sent</h2>
        <hr>
        <p>We've emailed you instructions for setting your password, if an account exists with the email you entered. You
            should receive them shortly.<br>If you don't receive an email, please make sure you've entered the address you
            registered with, and check your spam folder.</p>
    </div>

{% endblock %}

yatube/templates/users/password_reset_form.html
{% extends "base.html" %}
{% load static %}
{% block title %}Сброс пароля{% endblock %}


{% block content %}

    {% load user_filters %}

    <!--Reset Password-->
    <div class="container p-5">
        <h2 class="font-weight-bold mt-3">Reset Password</h2>
        <hr>
        <p>Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.</p>
        <form method="POST">
            {% csrf_token %}
            {{ password_reset_form }}
            <button class="btn btn-primary" type="submit">Send email</button>
        </form>
    </div>

{% endblock %}

yatube/templates/users/sendmail.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
            crossorigin="anonymous"
        />
        <title>Send Email</title>
    </head>
    <body>
        {% if messageSent %}
            <div class="container">
                <h3><strong>Email successfully sent</strong></h3>
                <p>Your message was successfully sent to {{ form.cleaned_data.to }}</p>
            </div>
        {% else %}
            <div class="container">
                <h3><strong>Send E-mail</strong></h3>

                <form method="post">
                    {% csrf_token %} {{ form.as_p }}
                    <br/>
                    <div class="text-center">
                        <input
                            type="submit"
                            class="btn btn-secondary"
                            style="width: 100%"
                            value="Send e-mail"
                        />
                    </div>
                </form>
            </div>
        {% endif %}
    </body>
</html>

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">
                Зарегистрироваться
            </div>
            <div class="card-body">
                {% include 'includes/form_errors.html' %}
                <form method="post" action="{% url 'users:signup' %}">
                    {% csrf_token %}
                    {% include 'includes/fields_form.html' %}
                    <div class="col-md-6 offset-md-4">
                        <button type="submit" class="btn btn-primary">
                            Зарегистрироваться
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}